services:
  postgres:
    image: postgres:16
    container_name: weather-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather-net

  mongo:
    image: mongo:6
    container_name: weather-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: weatherdb
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - weather-net

volumes:
  pgdata:
  mongodata:

networks:
  weather-net: