spring:
  application:
    name: weather-2
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: weatheruser
    password: secret123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
openweather:
  weather: https://api.openweathermap.org/data/2.5/weather
  location: http://api.openweathermap.org/geo/1.0/direct
  key: a6a16c2b63141f72e9503604b2ce6cba
